name: Build LaTex Document

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: pitch.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Pitch PDF
          path: pitch.pdf